source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'YLDropDownMenuViewTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UICollectionVCTest

pod 'AFNetworking'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'ReactiveObjC', '~> 3.0.0'
pod 'MJExtension'
pod 'CocoaLumberjack'
pod 'JKCategories'
pod 'OpenUDID'
pod 'DZNEmptyDataSet',        '1.8.1',          :inhibit_warnings => true

end
