source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'YLDropMenuTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UICollectionVCTest

pod 'Masonry'

end
